library(dplyr)
library(lubridate)
data <- read.table('./household_power_consumption.txt',header=TRUE,sep = ';',na.strings = '?')
data $Date <-dmy(data$Date)
feb <- filter(data,Date=='2007-02-01' | Date == '2007-02-02')
png(filename = 'plot1.png',width = 480,height = 480,units = 'px')
with(feb,hist(Global_active_power,main = 'Global Active Power',col='red',xlab = 'Global Active Power (kilowatts)'))
dev.off()
