library(dplyr)
library(lubridate)

data <- read.table('./household_power_consumption.txt',header=TRUE,sep = ';',na.strings = '?')
data $Date <-dmy(data$Date)
feb <- filter(data,Date=='2007-02-01' | Date == '2007-02-02')
feb$Datetime <- as.POSIXct(paste(feb$Date, feb$Time), format="%Y-%m-%d %H:%M:%S")
png(filename = 'plot2.png',width = 480,height = 480,units = 'px')
with(feb,plot(Datetime,Global_active_power,type='l',xlab='',ylab='Global Active Power (kilowatts)'))
dev.off()